### ISSUE TITLE
Publish .ipa release?

### ISSUE THREAD

**Issue by Johnny5sword** [Hecsall/MAPI#2] opened 2022-09-21 14:31 UTC
Hello!

It would be great if the .ipa is available so iOS users can install this app using [Altstore](https://altstore.io/)(iOS 12.2+) or [Sideloadly](https://sideloadly.io/)(iOS 7+).

Unfortunately, I can't build it myself because I don't have a Mac or know others who have one.

If it is released, I also hope it lowers min iOS version to have compatibility with iOS 9.3 because it's the last OS version available for my device.
Thank you!

Edit: It looks like [Flutter SDK](https://docs.flutter.dev/development/tools/sdk/releases?tab=macos) versions [2.10.5](https://storage.googleapis.com/flutter_infra_release/releases/stable/macos/flutter_macos_2.10.5-stable.zip)(Stable), April 2022 and [2.13.0-0.4.pre](https://storage.googleapis.com/flutter_infra_release/releases/beta/macos/flutter_macos_2.13.0-0.4.pre-beta.zip)(Beta), May 2022 were the last releases to support arm7v 32-bit iOS such as my version of iOS 9 based from this [document](https://docs.google.com/document/d/1Xz8B2w42ZGmrSdvQHo6LVLhiSZBIxnHxZxoZ-8oyRUc/mobilebasic).

**Comment by Hecsall** [comment] 2022-10-03 10:14
Hi @Johnny5sword, I'm not currently working on the app but I checked your suggestion, and it seems like XCode doesn't give the possibility to set a version prior to iOS 11, and I guess that Flutter and all its dependencies would not work anyway.

Speaking about the .ipa, since I don't have a paid developer account I cannot build a package "as intended", I found some guide on how to package a .ipa file starting from the output of a flutter build command, but when I tried it in the past it didn't let me install the .ipa, so I abandoned that idea.
I wanted to try again today, but XCode is giving me trouble with certificates, if I manage to do something about that I'll post an update on this issue.

For now, I'll close the issue, but thank you for your interest!

**Closed by Hecsall** 2022-10-03 10:14 UTC
